### PR TITLE
Add version to command line and user agent string

### PR DESCRIPTION
**Pull request by jimisola**
PR will:

* add -V/--version to command line: https://github.com/hamnis/maven-artifact/issues/30
* add version to user agent string: https://github.com/hamnis/maven-artifact/issues/25

### CODE REVIEW

**Review by hamnis — APPROVED** [review]

**Comment by hamnis** [comment]
Thanks. :)

**Comment by hamnis** [comment]
@jimisola you need a new relase with this?

**Comment by jimisola** [comment]
No stress on my behalf. Did you test it?
Would have liked to write some automated tests but.. I did some manual tests though, but nice to know that someone else tried it.

**Comment by jimisola** [comment]
@hamnis Any chance of making a new release?

**Pull request merged**
