### PR TITLE
feat: Create GitHub actions for build and deploy

### PR DESCRIPTION
**Pull request by jimisola**
This PR adds:

1. GitHub actions for build and publish to pypi.org (test and production) that uses hatch and `gh-action-pypi-publish` GitHub action
3. dependabot checks for updatessto python packages (pip) and GitHub Actions

Please not that the PR is not fully functional as I'm unable to actually test:

1. Publishing to pypi.org (tokens need to be set as GitHub Secrets or by using trusted publisher)
   1. pypi [apitoken](https://pypi.org/help/#apitoken) [trusted publishers](https://docs.pypi.org/trusted-publishers/)
   2. [github-action info](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github)
 2. Signing with GPG (can handled using `gh-action-pypi-publish` GitHub Action
 3. I did not activate testing (pytest) or linting (black and flake8) because I didn't see any unit tests and I'm not sure what formatting/linting you used before.
 
Relates: https://github.com/hamnis/maven-artifact/issues/10

### CODE REVIEW

**Comment by lfvjimisola** [comment]
@hamnis If you merge this PR it will build but not publish (PYPI tokens have to be added) as you can see here:

https://github.com/jimisola/maven-artifact/actions/runs/4953761009/jobs/8861580015

**Comment by hamnis** [comment]
Nice. Will have a closer look of this during the weekend.

Maybe the release should only trigger on push of tags?

**Comment by jimisola** [comment]
Yes, it is in setup like that in the GitHub actions:


For pypi publish tag with vX.Y.Z.
For pypi test

**Comment by hamnis** [comment]
Seems like this still contains the previous PR. Can you please rebase on master?

**Comment by hamnis** [comment]
I have added the required secrets, so hopefully this should work.

**Review by hamnis — APPROVED** [review]

**Comment by hamnis** [comment]
Seems like any subsequent builds causes error in pypi as we upload the same version twice.
Is there a way to include the git-sha on  test builds?

**Comment by jimisola** [comment]
> Seems like any subsequent builds causes error in pypi as we upload the same version twice. Is there a way to include the git-sha on test builds?

Looking at it now.

**Comment by jimisola** [comment]
Haven't found anyway to use the git-sha. However,

https://github.com/pypa/gh-action-pypi-publish#tolerating-release-package-file-duplicates

```
 with:
     skip-existing: true

```
Found no other solutions here:
* https://stackoverflow.com/questions/72661025/github-action-publishing-to-both-testpypi-and-pypi-fails
* https://github.com/pypa/gh-action-pypi-publish/issues/16

**Pull request merged**
