### PR TITLE
feat: Add MWE unit/integ tests and gh actions

### LINKED ISSUE #13: Add initial unit tests and configure with GitHub Actions
Create a MWE with:

- [ ] Unit tests
- [ ] GitHub Actions

### PR DESCRIPTION
**Pull request by jimisola**
Closes #13

Adds initial MWE for unit/integ test and github actions.

Additional tests, can now be added more easily with the  basic structure in place.

### CODE REVIEW

**Comment by jimisola** [comment]
Missed to format the code :) The system works. One sec.

**Comment by jimisola** [comment]
Should be ready for merge now.

I found some other stuff codewise but more towards nitpicking.

**Comment by jimisola** [comment]
@hamnis Pls let me know if I can be of any assistance to get this merged.

**Review by hamnis — APPROVED** [review]

**Comment by hamnis** [comment]
thanks for the ping, forgot about this.

**Pull request merged**
